# Generated by Django 6.0.3 on 2026-06-02 15:27

import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_file',
            field=models.FileField(upload_to=reports.models.report_upload_path),
        ),
    ]
