# Generated by Django 6.0.5 on 2026-06-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=200)),
                ('link', models.URLField(unique=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('executive_summary', models.TextField(blank=True, null=True)),
                ('key_findings', models.TextField(blank=True, null=True)),
                ('why_this_matters', models.TextField(blank=True, null=True)),
                ('doctor_perspective', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
